# Generated by Django 5.0.1 on 2024-01-11 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bids', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bids',
            name='reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
