# Generated by Django 5.0.1 on 2024-01-11 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bids', '0002_bids_reason'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bids',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Bids'},
        ),
        migrations.AddField(
            model_name='bidshistory',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
