# Generated by Django 5.0.1 on 2024-01-11 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bids', '0003_alter_bids_options_bidshistory_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='bidshistory',
            name='reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
