# Generated by Django 5.0.1 on 2024-01-12 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bids', '0005_bids_status_bidshistory_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bidshistory',
            options={},
        ),
    ]
